CREATE TABLE Time (
	day DATE,
	time TIME
);

CREATE FUNCTION daysSince (d DATE)
RETURNS INTEGER DETERMINISTIC
RETURN DATEDIFF(CURDATE(), d);

CREATE FUNCTION hoursSince (t TIME)
RETURNS INTEGER DETERMINISTIC
RETURN HOUR(TIMEDIFF(CURTIME(), t));

CREATE FUNCTION secsSince (t TIME)
RETURNS INTEGER DETERMINISTIC
RETURN TIME_TO_SEC(TIMEDIFF(CURTIME(), t));

CREATE VIEW TimeSince AS
SELECT *, daysSince(day), hoursSince(time), secsSince(time)
FROM Time;
